pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stages {
        stage('DB') {
            agent {
                docker { 
                    image 'mysql:latest' // Adjust version as needed
                    args '-e MYSQL_ROOT_PASSWORD=password' // Provide appropriate MySQL root password
                }
            }
            steps {
                script {
                    def sqlCmd = "mysql -h host -u user -ppassword -e 'SELECT * FROM XYZ;' database_name"
                    def result = sh(script: sqlCmd, returnStdout: true).trim()
                    echo "Query result: ${result}"
                }
            }
        }
    }
}
